/*
 * This file is generated by jOOQ.
 */
package com.example.database.generatedclasses;


import com.example.database.generatedclasses.tables.Book;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in mydatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BOOK_AUTHOR_ID = Internal.createIndex(DSL.name("author_id"), Book.BOOK, new OrderField[] { Book.BOOK.AUTHOR_ID }, false);
}
