/*
 * This file is generated by jOOQ.
 */
package com.example.database.generatedclasses;


import com.example.database.generatedclasses.tables.Author;
import com.example.database.generatedclasses.tables.Book;
import com.example.database.generatedclasses.tables.Databasechangelog;
import com.example.database.generatedclasses.tables.Databasechangeloglock;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mydatabase extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydatabase</code>
     */
    public static final Mydatabase MYDATABASE = new Mydatabase();

    /**
     * The table <code>mydatabase.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>mydatabase.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>mydatabase.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>mydatabase.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * No further instances allowed
     */
    private Mydatabase() {
        super("mydatabase", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK
        );
    }
}
