/*
 * This file is generated by jOOQ.
 */
package com.example.database.generatedclasses;


import com.example.database.generatedclasses.tables.Author;
import com.example.database.generatedclasses.tables.Book;
import com.example.database.generatedclasses.tables.Databasechangelog;
import com.example.database.generatedclasses.tables.Databasechangeloglock;


/**
 * Convenience access to all tables in mydatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>mydatabase.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>mydatabase.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>mydatabase.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>mydatabase.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;
}
