spring.application.name=demo

# Database
# Take values from pom.xml

# Use root values otherwise getting Access denied for user 'username'@'172.20.0.1' (using password: YES)
# And cba to fix rn
db.url=@db.url@
db.username=@db.root.username@
db.password=@db.root.password@
db.driver=@db.driver@

spring.liquibase.change-log=classpath:db/changelog.sql