/*
 * This file is generated by jOOQ.
 */
package com.example.demo.generatedclasses;


import com.example.demo.generatedclasses.tables.Author;
import com.example.demo.generatedclasses.tables.Book;


/**
 * Convenience access to all tables in mydatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mydatabase.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>mydatabase.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
